apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-playground
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - keycloak.yaml
  - search-service.yaml
  - mail-service.yaml
  - deduplication-service.yaml
  - user-service.yaml
  - gateway-yarp.yaml
  - gateway-ocelot.yaml
  - monolith.yaml
  - ingress.yaml
configMapGenerator:
  - name: keycloak-realm
    files:
      - realm-export.json
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/part-of: gateway-playground
    includeSelectors: true
